# Navigation Links
main:
  - name: Bio
    url: /
    weight: 10
  - name: Experience
    url: /#experience
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
#  - name: Papers  <-- 等你有论文发表时，去掉这行的 # 号即可显示
#    url: /#papers
#    weight: 40
